### ISSUE TITLE
Create API endpoint for intents

### ISSUE THREAD

**Issue by BrunaNayara** [lappis-unb/BotFlow#5] opened 2019-06-03 19:08 UTC
Create API endpoint to download intents file

**Tasks**

- [ ] Create API endpoint
- [ ] Get all intents from database
- [ ] Write all intents in md file

**Acceptance criteria**

- [ ] Be able to download intents file
- [ ] Document on swagger

**Comment by rodmaia2099** [comment] 2019-07-29 17:15
Duplicate of #9

**Closed by rodmaia2099** 2019-07-29 17:15 UTC
Labels: API, question
